version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080" # Maps port 8000 on the host to port 8080 in the backend container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080

  frontend:
    build:
      context: .
      dockerfile: MyAngularApp/Dockerfile
    ports:
      - "4200:8080" # Maps port 4200 on the host to port 8080 in the frontend container
